
class JiraEndpoints:
    def __init__(self, host):
        api = f'{host}/rest/api/2'
        self.endpoint = {
            # Myself
            'get_current_user': f'{api}/myself',
            # Fields
            'get_fields':
                f'{api}/field',
            'create_custom_field':
                f'{api}/field',
            'get_all_issue_field_options':
                f'{api}/field/{{}}/option',
            'create_issue_field_option':
                f'{api}/field/{{}}/option',
            'get_issue_field_option':
                f'{api}/field/{{}}/option/{{}}',
            'update_issue_field_option':
                f'{api}/field/{{}}/option/{{}}',
            'delete_issue_field_option':
                f'{api}/field/{{}}/option/{{}}',
            'replace_issue_field_option':
                f'{api}/field/{{}}/option/{{}}/issue',
            'get_selectable_issue_field_options':
                f'{api}/field/{{}}/option/suggestions/edit',
            'get_visible_issue_field_options':
                f'{api}/field/{{}}/option/suggestions/search',
            # Issue
            'create_issue':
                f'{api}/issue',
            'get_issue':
                f'{api}/issue/{{}}',
            'edit_issue':
                f'{api}/issue/{{}}',
            'delete_issue':
                f'{api}/issue/{{}}',
            'assign_issue':
                f'{api}/issue/{{}}/assignee',
            'add_attachment':
                f'{api}/issue/{{}}/attachments',
            'get_change_logs':
                f'{api}/issue/{{}}/changelog',
            'get_comments':
                f'{api}/issue/{{}}/comment',
            'add_comment':
                f'{api}/issue/{{}}/comment',
            'get_comment':
                f'{api}/issue/{{}}/comment/{{}}',
            'update_comment':
                f'{api}/issue/{{}}/comment/{{}}',
            'delete_comment':
                f'{api}/issue/{{}}/comment/{{}}',
            'get_edit_issue_meta':
                f'{api}/issue/{{}}/editmeta',
            'notify':
                f'{api}/issue/{{}}/notify',
            'get_issue_property_keys':
                f'{api}/issue/{{}}/properties',
            'get_issue_property':
                f'{api}/issue/{{}}/properties/{{}}',
            'set_issue_property':
                f'{api}/issue/{{}}/properties/{{}}',
            'delete_issue_property':
                f'{api}/issue/{{}}/properties/{{}}',
            'get_remote_issue_links':
                f'{api}/issue/{{}}/remotelink',
            'create_or_update_remote_issue_link':
                f'{api}/issue/{{}}/remotelink',
            'delete_remote_issue_link_by_global_id':
                f'{api}/issue/{{}}/remotelink',
            'get_remote_issue_link_by_id':
                f'{api}/issue/{{}}/remotelink/{{}}',
            'update_remote_issue_link':
                f'{api}/issue/{{}}/remotelink/{{}}',
            'delete_remote_issue_link_by_id':
                f'{api}/issue/{{}}/remotelink/{{}}',
            'get_transitions':
                f'{api}/issue/{{}}/transitions',
            'do_transition':
                f'{api}/issue/{{}}/transitions',
            'get_votes':
                f'{api}/issue/{{}}/votes',
            'add_vote':
                f'{api}/issue/{{}}/votes',
            'remove_vote':
                f'{api}/issue/{{}}/votes',
            'get_issue_watchers':
                f'{api}/issue/{{}}/watchers',
            'add_watcher':
                f'{api}/issue/{{}}/watchers',
            'remove_watcher':
                f'{api}/issue/{{}}/watchers',
            'get_issue_worklog':
                f'{api}/issue/{{}}/worklog',
            'add_worklog':
                f'{api}/issue/{{}}/worklog',
            'get_worklog':
                f'{api}/issue/{{}}/worklog/{{}}',
            'update_worklog':
                f'{api}/issue/{{}}/worklog/{{}}',
            'delete_worklog':
                f'{api}/issue/{{}}/worklog/{{}}',
            'get_worklog_property_keys':
                f'{api}/issue/{{}}/worklog/{{}}/properties',
            'get_worklog_property':
                f'{api}/issue/{{}}/worklog/{{}}/properties/{{}}',
            'set_worklog_property':
                f'{api}/issue/{{}}/worklog/{{}}/properties/{{}}',
            'delete_worklog_property':
                f'{api}/issue/{{}}/worklog/{{}}/properties/{{}}',
            'create_issues':
                f'{api}/issue/bulk',
            'get_create_issue_meta':
                f'{api}/issue/createmeta',
            'get_issue_picker_resource':
                f'{api}/issue/picker',
        }
